### PR TITLE
Move scheduler initialization out of line.

### PR DESCRIPTION
**Pull request by alkis**
```diff
 name           control ns/iter  new ns/iter  diff ns/iter  diff %  speedup
-smoke_bench    95,092,190       96,296,706      1,204,516   1.27%   x 0.99
+smoke_bench_1  10,265,118       10,150,296       -114,822  -1.12%   x 1.01
+smoke_bench_2  14,199,750       13,289,244       -910,506  -6.41%   x 1.07
+smoke_bench_3  12,718,608       11,759,877       -958,731  -7.54%   x 1.08
+spawn_bench    1,091,394        1,051,427         -39,967  -3.66%   x 1.04
+spawn_bench_1  856,703          832,541           -24,162  -2.82%   x 1.03
+yield_bench    6,207,276        5,747,623        -459,653  -7.41%   x 1.08
```

### CODE REVIEW

**Comment by Xudong-Huang** [comment]
thanks! I'm wondering why move out the init code could run faster?

**Comment by alkis** [comment]
There is a lot less code inlined in `get_scheduler()` and `get_scheduler()` is called from many places.

**Comment by Xudong-Huang** [comment]
But it will return immediately, I think the run time logic is the same.
Anyway the logic is cleaner than before.

**Comment by Xudong-Huang** [comment]
thanks! I learned new things here 👍

**Pull request merged**
